# PR-01 Data Wrangling-I

## The libraries we frequently use in Data Science:
- **NumPy**: The fundamental package for scientific computing in Python, providing support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions.
- **Pandas**: Offers essential high-level data structures, such as DataFrames, and tools for efficient data manipulation, cleaning, analysis, and preparation.
- **SciPy**: Built on NumPy, this library provides a collection of algorithms and functions for scientific and technical computing, including modules for optimization, integration, linear algebra, and signal processing.
- **Matplotlib**: A versatile and widely used 2D plotting library for creating static, animated, and interactive visualizations (line plots, histograms, scatter plots, etc.).
- **Seaborn**: Built on top of Matplotlib, Seaborn provides a high-level interface for drawing attractive and informative statistical graphics, integrating seamlessly with Pandas DataFrames.
- **Plotly**: An excellent library for creating interactive, web-based visualizations and dashboards that can be embedded in web applications or Jupyter notebooks.
- **Bokeh**: Another powerful library for creating interactive, web-ready visualizations, with a focus on high-performance interactivity over large or streaming datasets.

## We will be accessing the datasets from Kaggle

We are using the simple Titanic Dataset accessible from: https://www.kaggle.com/datasets/yasserh/titanic-dataset as this is a versatile dataset and used frequently as a beginner Data Science Assignment by people who are starting out with Data Science.

**Why Titanic Dataset?**

The Titanic dataset is a well-known dataset obtained from Kaggle, based on information about passengers who traveled on the RMS Titanic. The dataset is commonly used in data analysis, preprocessing, and machine learning to study factors affecting passenger survival.

Each row in the dataset represents one passenger, and each column represents a specific attribute related to that passenger, such as demographic details, travel class, and survival status.

The primary objective of this dataset is to analyze patterns in survival and identify which factors (such as age, gender, and passenger class) influenced the chances of survival during the disaster.

We will use pandas to import the "csv" dataset into out python notebook as it provides the tools needed to import, structure, clean, and analyze data efficiently within the interactive notebook environment.

In [1]:
import pandas as pd

# Use the exact filename if it's in the same directory as the notebook
df = pd.read_csv('The Titanic dataset.csv')

# Verify the data loaded correctly
df.head()

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90

We will notice that this code snippet only loads the first 4 rows of the dataset. Going forward we will manipulate data to met our needs accordingly. Let's start with displaying the entire dataset.

### Data Preprocessing:
- Check Dimension of the Dataset:

In [3]:
df.shape

(1302, 10)

- Check Data Types of Variables:

In [5]:
df.dtypes

1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
dtype: object

- Statistical Summary:

In [6]:
df.describe()

           1     2     3            4     5     6     7     8     9         10
count   1302  1302  1302         1301  1301  1045  1300  1300  1296       1302
unique  1301     4     3         1297     3    98    10   283     4       1301
top        1     3     0  Mr. Anthony  male    24     0    13     S  01-Jan-90
freq       2   700   801            2   835    47   781    59   905          2

- Count of missing values per column:

In [29]:
df.isnull().sum()

sn            0
pclass        0
survived      0
name          1
gender        1
age         257
family        2
fare          0
embarked      6
date          0
dtype: int64

### Data Formatting:
- Replace the Fare column with mean:

### What is being done?
- The dataset was loaded and inspected and all the column names were stripped off their leading and trailing spaces using and also all the column names were to be converted to lowercase:
```
df.columns = df.columns.str.strip().str.lower()
```
- But, when the column names were listed, it returned this:
```
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
```
So, we renamed the columns as:
```
df.columns = [
    'sn', 'pclass', 'survived', 'name', 'gender',
    'age', 'family', 'fare', 'embarked', 'date'
]
```
- After this, we realised that all the values in the fare column were objects, so we couldn't perform any numeric operations on that column, so we converted all the values in this column to numeric data type (integer/float):
```
df['fare'] = pd.to_numeric(df['fare'], errors='coerce')
```
- After that, we finally replaced all the null values in the fare column with the mean values:
```
df['fare'].fillna(df['fare'].mean(), inplace=True)
```

In [12]:
df.columns = df.columns.str.strip().str.lower()

In [13]:
df.columns.tolist()

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [17]:
df.columns = [
    'sn', 'pclass', 'survived', 'name', 'gender',
    'age', 'family', 'fare', 'embarked', 'date'
]

In [18]:
df.columns

Index(['sn', 'pclass', 'survived', 'name', 'gender', 'age', 'family', 'fare',
       'embarked', 'date'],
      dtype='object')

In [23]:
df['fare'] = pd.to_numeric(df['fare'], errors='coerce')

In [27]:
df['fare'].isnull().sum()
df['fare'].dtype

dtype('float64')

**In the Titanic dataset, fare prices are closely tied to the ticket class. Using a global median might overestimate the fare for a missing 3rd-class passenger or underestimate it for a 1st-class one. This group-based approach provides a more statistically accurate imputation**

In [34]:
df['fare'] = df['fare'].fillna(df.groupby('pclass')['fare'].transform('median'))

In [35]:
df.head(20)

,sn,pclass,survived,name,gender,age,family,fare,embarked,date
0,sn,pclass,survived,NaN,gender,age,family,33.462182,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.550000,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.550000,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.250000,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,33.462182,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2,20.250000,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16,0,7.650000,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25,0,7.650000,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30,1,24.000000,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28,1,24.000000,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20,0,7.925000,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18,0,7.229200,C,10-Jan-90
12,11,3,0,"Adahl, Mr. Mauritz Nils Martin",male,30,0,7.250000,S,11-Jan-90
13,12,3,0,"Adams, Mr. John",male,26,0,8.050000,S,12-Jan-90
14,13,3,0,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40,1,9.475000,S,13-Jan-90
15,14,3,1,"Aks, Master. Philip Frank",male,0.83,1,9.350000,S,14-Jan-90
16,15,3,1,"Aks, Mrs. Sam (Leah Rosen)",female,18,1,9.350000,S,15-Jan-90
17,16,3,1,"Albimona, Mr. Nassef Cassem",male,26,0,18.787500,C,16-Jan-90
18,17,2,0,"Aldworth, Mr. Charles Augustus",male,30,0,13.000000,S,17-Jan-90
19,18,3,0,"Alexander, Mr. William",male,26,0,7.887500,S,18-Jan-90